import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react"
import localFont from "next/font/local";

import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import { auth } from "@/auth";

import { QueryProvider } from "@/providers/query-provider";
import { ModalProvider } from "@/providers/modal-provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth()
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider session={session}>
          <QueryProvider>
            {children}
            <Toaster />
            <ModalProvider />
          </QueryProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
